[build]
builder = "nixpacks"

[build.nixpacksConfig]
phases.install.cmds = ["pip install --force-reinstall --no-cache-dir google-generativeai==0.3.1", "pip install -r requirements.txt"]
phases.setup.aptPkgs = ["libmagic1", "libmagic-dev", "file"]

[deploy]
startCommand = "uvicorn webapp.app:app --host 0.0.0.0 --port $PORT --workers 2"